--- #YAML:1.0
name:                SMS-Send-US-SprintPCS
version:             0.03
abstract:            An SMS::Send driver for the messaging.sprintpcs.com website
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    SMS::Send:                     0
    Test::More:                    0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joshua ben Jore <jjore@cpan.org>
